# Generated by Django 5.0.14 on 2026-03-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_order_seller_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_seen',
        ),
    ]
